spring:
  # redis 配置
  redis:
    # 地址
#    host: 8.130.98.215
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
#    password: 123321
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qihang-erp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Andy_123
  


# # mybatis 日志
# mybatis-plus:
#     configuration:
#       log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志


# minio配置
minio:
  endpoint: http://127.0.0.1:9000 #换成自己的minio服务端地址
  accessKey: 0AksAWDtI20Lpb4qxq5S
  secretKey: yOAZkOVwrhPooBRel5PB0GwS5uw8VAgmqYykHl3T
  secure: false
  bucketName: ecerp